[package]
name = "minicache"
version = "0.1.0"
description = "A minimalistic in-memory cache with async support"
homepage = "github.com/imduchuyyy/minicache"
respository = "github.com/imduchuyyy/minicache"
readme = "README.md"
keywords = ["cache", "in-memory", "async", "rust"]
categories = ["asynchronous", "data-structures", "performance"]
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1.0"
axum = "0.8.7"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "cache_bench"
harness = false
